name: CI
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            vcpkgCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
            preset: 'windows'
          - os: ubuntu-22.04
            vcpkgCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
            preset: 'unix'
          - os: macos-12
            vcpkgCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
            preset: 'unix'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set C++/C compiler on macOS
        shell: bash
        run: echo "CC=$(brew --prefix llvm@14)/bin/clang" >> $GITHUB_ENV; echo "CXX=$(brew --prefix llvm@14)/bin/clang++" >> $GITHUB_ENV; cat "$GITHUB_ENV"
        if: runner.os == 'macOS'

      - uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: ${{ matrix.vcpkgCommitId }}
          cache: true

      - name: GCC version on Linux
        shell: bash
        run: g++ --version
        if: runner.os == 'Linux'

      - name: Run CMake with manifest mode vcpkg
        shell: bash
        run: cmake --preset=${{ matrix.preset }} -B build -DSignal_Test=1 -DSignal_Example=1 -DCMAKE_VERBOSE_MAKEFILE=1

      - name: Compile binaries
        shell: bash
        run: cmake --build build

      - name: Run tests
        shell: bash
        run: ctest --test-dir build/Signal_Test

      - name: Run example on Linux/macOS
        shell: bash
        run: ./build/Signal_Example/Signal_Example
        if: runner.os == 'Linux' || runner.os == 'macOS'
